kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devnet
nodes:
- role: control-plane
  extraPortMappings:
  # Yelb App
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  # Sock-Shop App
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker